### ISSUE TITLE
Set memory limit?

### ISSUE THREAD

**Issue by linsyking** [binpash/try#121]
Is there a way to set the memory limit when executing the command?

**Comment by ericzty** [comment]
Hi, currently there is no way to set the memory limit when executing a command. The tool you’re looking for is [control groups](https://docs.kernel.org/admin-guide/cgroup-v1/cgroups.html).

Currently there are no plans to implement try with cgroups, but I’ll circle in @angelhof to see if this would be a good idea, since limiting process resource usage *may* help when we’re running a lot in parallel.

**Comment by angelhof** [comment]
I agree with @ericzty that there are no plans to implement memory limits in `try` soon since this is orthogonal to try's goals.
