### ISSUE TITLE
Hardened mode?

### ISSUE THREAD

**Issue by ericzty** [binpash/try#55]
Perhaps a flag for a hardened mode which uses a separate network stack and only expose *some* /dev files (e.g., null, (u)random, zero).

Something that makes `sudo ./try rm -rf /` not affect the host system.

**Comment by ericzty** [comment]
@mgree Thoughts?

**Comment by mgree** [comment]
I think we shouldn't call anything `try` does 'hardened', because that seems to make a security claim we're not really going to be able to backup.

But I think there are good moves to make in this direction:

 - We should have tests that do really risky things (in CI).

 - We should by default only be mapping [the safe `/dev` files I outlined before](https://github.com/binpash/try/pull/14#issuecomment-1577537098).

 - I don't think the separate network stack is super material here, though having a flag to turn off network access makes sense.

**Comment by mgree** [comment]
All of this has been done except for #127.
